[workspace]
members = ["ctypes", "macros", "macros-core"]

[package]
name = "drone-core"
version = "0.14.2"
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
edition = "2018"
resolver = "2"
repository = "https://github.com/drone-os/drone-core"
homepage = "https://www.drone-os.com/"
documentation = "https://api.drone-os.com/drone-core/0.14/drone_core/"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = [
    "async",
    "real-time",
    "bare-metal",
    "rtos",
    "firmware",
]
categories = [
    "embedded",
    "asynchronous",
    "concurrency",
    "no-std",
    "os",
]
description = """
The core crate for Drone, an Embedded Operating System.
"""

[badges]
maintenance = { status = "actively-developed" }

[features]
default = []
lang-items = ["log"]
log = []
trace = ["log"]

[dependencies.drone-ctypes]
version = "=0.14.2"
path = "ctypes"

[dependencies.drone-core-macros]
version = "=0.14.2"
path = "macros"

[dependencies]
atomic = "0.5"
futures = { version = "0.3", default-features = false, features = ["alloc", "async-await"] }
typenum = "1.12"
